### ISSUE TITLE
R4i Gold 3ds rts from r4ids.cn nos showing up

### ISSUE THREAD

**Issue by AlbertoSempai** [ntrteam/flashcart_core#135]
Okay, I know I probably shouldn't write this here, but I'm kind of desperate and new to the platform.

I bought a r4i gold 3ds rts, which has the link r4ids.cn on the front. I managed it to work on both a dsi with Hiya CFW and an updated old 3ds with luma and ntrlauncher. The problem is that after one hour of play more or less it stopped working and now it does not show up at all in neither the 3ds or the dsi.

I have searched up for many, many ways to fix it, but I haven't achieved it yet. I use the newest kernel in http://r4ids.cn/r4i-download-e.htm (which is V1.64). I have tried to clean everything I can, but it is in vane. Every other cartridge works perfectly fine, even other flashcard I have (M3DS Real), and it isn't a problem of the microSD neither (tried 4 of them, each formatted with Panasonic SD Card Formatter, and got no result.

Is my card definitely broken?

Thanks a lot, I appreciate any answer.

**Comment by hedgeberg** [comment]
So, first off you're right, this isn't the place to ask this question, and in general when you have this kind of question that isn't about tool problems or bad documentation, it shouldn't be placed on the issues section on GitHub. This is an issue that would be much better handled in the hardware support channel of the Nintendo Homebrew discord server. 

The ntrboot installer has certain debug controls that can be used to diagnose this kind of issue, if I recall correctly. Despite contributing to the project I have basically 0 memory of how this works since we haven't pushed an update in like, over a year. People in the NH server however would likely be more able to walk you through this process.

**Comment by hedgeberg** [comment]
(for what it's worth, I am on that server as well. if noone responds to you for over 20 minutes, feel free to @ me and I'll help you out when I have a chance. Good luck, know this kind of thing can be frustrating)
