### ISSUE TITLE
R4i Gold rev4 (r4ids.com)

### ISSUE THREAD

**Issue by alexandreh54** [ntrteam/flashcart_core#40]
ChipID: 00000FC2
HW Revision: 00000000

This flashcart seems to be a clone of the R4i Gold from r4ids.cn
It is very similar to this flashcart : https://github.com/kitling/flashcart_core/issues/21

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![20170828_214639 medium](https://user-images.githubusercontent.com/19622850/29792317-54258262-8c40-11e7-9235-682618108bf4.jpg)

![20170828_114911 medium](https://user-images.githubusercontent.com/19622850/29792314-541e2b0c-8c40-11e7-8f07-09f205c08037.jpg)

![20170828_214917 medium](https://user-images.githubusercontent.com/19622850/29792318-543ce7c2-8c40-11e7-9aa9-96f57d3fe0a8.jpg)

</p></details> 

Updater : <a href="https://mega.nz/#!C0hxTRzL!hVaxdDUR5n-4l7bdTkkiiaaUxlggtoDDBekgWz8AZoM">mega.nz</a>
GM9 Untrimmed Dump: <a href="https://mega.nz/#!qkwxQJZZ!_Gwd-QonFlfhum8L-tJMd7LjA-XHCpmDbr0qNbQ6G-M">mega.nz</a>

**Comment by dark-samus** [comment]
On the todo. Should be simple to support, other than the fact that we can't automatically identify it.

**Comment by zoogie** [comment]
I checked your files @alexandreh54 and the offsets and crypto match rev5 exactly. Either you can try my script on #21 or wait for dark-samus to finish official support. You should be able to reflash your card should the script's generated backup.bin not work. (you must trim the backup.bin's last 2MB off for it to work). It's a perfect mirror when comparing 0-0x1FFFFF --> 0x200000-0x3FFFFF.

**Comment by Xeon3D** [comment]
@zoogie's script worked for mine. My cart is exactly this one.

**Comment by Xeon3D** [comment]
This is the backup.bin that worked for my Rev. 4 cart with r4ids.com on the label.
[r4ids.com Rev.4.zip](https://github.com/kitling/flashcart_core/files/1369577/r4ids.com.Rev.4.zip)

Just uncompress it to SD:/ntrboot/, restore it with 
[this app](http://s000.tinyupload.com/index.php?file_id=00664373029281777476) (put it in SD:/luma/payloads/) and put safeB9Sinstaller.firm as ntrboot.firm on the SD card root.

All this was possible once again, thanks to @zoogie

**Comment by jason0597** [comment]
I was able to flash this flashcart sucessfully (and ofc tested it) using ds_ntrboot_flasher v4.0 and ntrboot_flasher (with the latest flashcart_core custom built)

**Comment by kitling** [comment]
Closing due to reports that it works.

**Comment by zoogie** [comment]
Everyone, could you please do me a favor? We need some info to help support more versions of the r4iGold. This is all you have to do:

After downloading this ntrboot_flasher.zip
Please insert your rev4-5, boot the app, press Y until you see "Log Level: DEBUG" in the bottom right of the top screen. Then "Dump Flash". The backup.bin dump isn't important, look at ntrboot.log in sdmc://ntrboot/ and tell us what number is after "[NOTICE]: R4iGold: HW C7 value = ". Also let us know what r4igold revision you have. Back of card over the right connector pin.

@kitling 
Sorry to bump this but since we have rev6-7 figured out, we need to get command C7 results from users to tell 6-7 apart from rev4-5.

**Comment by Xeon3D** [comment]
I have a Rev. 4 cart from r4ids.com and that version of ntrboot flasher says it is not supported.

**Comment by Xeon3D** [comment]
I built latest version and this is outputted from my Rev.4 card from r4ids.com : 

[NOTICE]: R4iGold: HW C7 value = a79bca95
